# Generated by Django 2.2.4 on 2019-08-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
