# Generated by Django 2.2.4 on 2019-09-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'why choose us', 'verbose_name_plural': 'why choose us'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
