# Generated by Django 2.2.4 on 2019-08-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
